name: BlackMoon Krnln OBJ

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  bmkrobj-debug-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Add msuild to local environment
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      # Test build
      - name: Build BlackMoon Krnln OBJ
        run: msbuild Project/krnln_VS2019_Obj.vcxproj /p:configuration=debug /p:platform=win32 -maxcpucount:4

  bmkrobj-release-win32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Add msuild to local environment
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      # Test build
      - name: Build BlackMoon Krnln OBJ
        run: msbuild Project/krnln_VS2019_Obj.vcxproj /p:configuration=release /p:platform=win32 -maxcpucount:4
